on: [push]

jobs:
  macos:
    runs-on: macos-latest
    name: Upterm in macos
    steps:
      - uses: actions/checkout@v3
      - uses: corvofeng/action-upterm@v3.4

  # ubuntu-job:
  #   runs-on: ubuntu-latest
  #   name: Upterm in ubuntu
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: corvofeng/action-upterm@v3.4

